---
- name: CVE-2024-3094 Check
  hosts: all_hosts
  gather_facts: true
  tasks:
    - name: Create results directory
      ansible.builtin.file:
        path: "./results"
        state: directory
        mode: '0755'

    - name: Check which version of XZ is installed
      ansible.builtin.command: xz --version
      register: xz_version
      changed_when: false

    - name: Check if the version of XZ is vulnerable
      ansible.builtin.command: strings `which xz` | grep '5\.6\.[01]'
      register: xz_vulnerable_version
      ignore_errors: true
      changed_when: false

    - name: Save xz version results to local file
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ xz_version.stdout }}"
        dest: "./results/{{ inventory_hostname }}_xz_version_results.txt"
        mode: '0644'

    - name: Save xz vulnerable version results to local file
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ xz_vulnerable_version.stdout }}"
        dest: "./results/{{ inventory_hostname }}_xz_vulnerable_version_results.txt"
        mode: '0644'

    - name: Copy JFrog program to remote host
      ansible.builtin.copy:
        src: "./cve-2024-3094-tools"
        dest: "{{ ansible_env.HOME }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0755'
        remote_src: false

    - name: Run JFrog program for more info
      ansible.builtin.command:
        chdir: "{{ ansible_env.HOME }}"
        cmd: ./cve-2024-3094-tools/cve-2024-3094-detector/cve-2024-3094-detector.sh
      register: cve_2024_3094_detector
      changed_when: false

    - name: Remove ANSI escape codes from the output
      ansible.builtin.set_fact:
        cleaned_output: "{{ cve_2024_3094_detector.stdout | regex_replace('\\x1B\\[[0-9;]*[mK]', '') }}"

    - name: Save JFrog program output to local file
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ cleaned_output }}"
        dest: "./results/{{ inventory_hostname }}_cve_2024_3094_detector_results.txt"
        mode: '0644'
