---
- name: Run commands and save output to local files
  hosts: all_hosts
  gather_facts: no
  tasks:
    - name: Check disk usage
      ansible.builtin.command: df -h
      register: disk_usage

    - name: Check memory usage
      ansible.builtin.command: free -m
      register: memory_usage

    - name: Save disk usage to local file
      delegate_to: localhost
      run_once: true
      ansible.builtin.copy:
        content: "{{ disk_usage.stdout }}"
        dest: "./disk_usage_results.txt"

    - name: Save memory usage to local file
      delegate_to: localhost
      run_once: true
      ansible.builtin.copy:
        content: "{{ memory_usage.stdout }}"
        dest: "./memory_usage_results.txt"
